
export const PRIMARY_COLOR = '#005F54'; 

export const MYSURU_AREAS = [
  "Vijayanagar", "Dattagalli", "J P Nagar", "Hootagalli",
  "Bogadi", "KRS Road", "Sriramapura", "Siddhartha Layout",
  "Hunsur Road", "Hebbal", "Kuvempu Nagar", "Rajiv Nagar",
  "Bogadi Road", "Sathagalli Layout", "Ramakrishna Nagar", "Rammanahalli",
  "Gokulam", "TK Layout", "T Narasipura Main Road", "Jayalakshmipuram",
  "Yadavagiri", "Ilavala Hobli", "BEML Nagar", "Bannimantap",
  "Kesare", "Vidyaranyapuram", "Roopa Nagar", "Nazarbad",
  "Sharadadevi Nagar", "Yaraganahalli", "Lalitha Mahal Palace", "Rajarajeshwari Nagar",
  "Alanahalli Layout", "Lakshmipuram", "KC Layout", "RT Nagar",
  "Udayagiri", "Bannur Road", "Bangalore Road", "Kalidasa Road",
  "JSS Layout", "Mahadevapura Road", "V. V. Mohalla", "Brindavan Extention",
  "Vivekananda Nagar", "Krishnarajasagara", "University Layout", "Nanjangud Highway",
  "Bannimantapa Road", "Kanakadasa Nagar", "Chamarajapuram", "Devanuru",
  "Saraswathipuram", "Niveditha Nagar", "Aravinda Nagar", "Bilikere",
  "Nadanahalli", "Chamundipuram", "N.R Mohalla", "Vishweshwara Nagar",
  "Ramanuja Road", "Elivala", "Mandi Mohalla", "M.S.Ramaiah Layout",
  "Kalyanagiri", "Bandipalya", "Jayanagar", "Nanjangudu",
  "Metagalli", "Kuppaluru", "Srinagara Layout", "Chamrajpura",
  "Shakti Nagar", "Alanahalli", "Tilak Nagar", "Hanchya",
  "Kote Hundi", "Kergalli", "Rajendra Nagar", "Vontikoppal",
  "Basavanahalli", "Huyilalu Road", "RS Naidu Nagar", "Gangothri Layout",
  "Somanath Nagar", "Ramachandra Agrahara", "Hinkal", "Naganahalli",
  "Kadakola", "Thaluru", "Bannur", "Elvala",
  "Dadaha Halli", "Sayyaji Rao Road", "Palahalli", "Madagalli",
  "Ittige Gudu", "Heggadadevankote", "Periyapatna", "Nagawala",
  "Hosahundi", "Rajajinagara", "Jantagalli", "Shivaji Road",
  "Beechanakuppe", "Adipampa Road", "Mentagalli Airport", "Jayalaxmipuram",
  "Airport Road", "Jettihundi", "Mirza Road", "Pragathi Nagar",
  "Rajeevnagar 2nd Stage", "Mogarahalli", "Ashokpuram", "Devaraja Mohalla",
  "Shyadanahalli", "Gaddige", "Bettadapura", "Halladakallahalli",
  "Utanahalli", "Bandipur", "Kabini",
  "Gundu Rao Nagar", "KR Pet", "KS Town", "Naguvanahalli",
  "Krishnamurthy Puram", "JC Nagar", "Kurubara Halli", "Madapura",
  "Vinayakanagara", "Marase", "Gayathripuram", "Jyothi Nagar",
  "Shankara Nagar", "Dadadahalli", "Huskur", "Tirumakudalu Narasipura",
  "Rangasamudra", "BMIC Road", "Hannahalli", "Karkanahalli Village",
  "100 feet road", "Bannmantap C Layout", "Khari Town", "Ganga Nagar",
  "Halalu", "Hadajana", "Gejjagalli", "Doddakaturu",
  "Murudagalli", "Varuna", "Bettagalli Road"
].sort();
